# -*- coding: utf-8 -*-
"""QuestionGen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nCsVnBELzI0tT9AxhABZhe09PqMANYaU

#1. Env Set Up
"""

!pip install -q \
  "requests==2.32.4" \
  langchain \
  langchain-core \
  langchain-openai \
  pydantic \
  python-dotenv

!pip check

# import os
# os.kill(os.getpid(), 9)

import os
import json
import warnings
import re
from dataclasses import dataclass
from typing import TypedDict, Literal, Optional, List

import pandas as pd
import numpy as np
import requests
from pydantic import BaseModel, Field

from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage
from langgraph.graph import StateGraph, START, END
# from langchain_core.output_parsers import StrOutputParser
# from langchain.chains import ConversationChain
# from langchain.memory import ConversationBufferMemory

warnings.filterwarnings("ignore", category=DeprecationWarning)

print("requests:", requests.__version__)

from google.colab import drive
drive.mount('/content/drive')

def load_api_keys(filepath="api_key.txt"):
    with open(filepath, "r") as f:
        for line in f:
            line = line.strip()
            if line and "=" in line:
                key, value = line.split("=", 1)
                os.environ[key.strip()] = value.strip()

path = '/content/drive/MyDrive/Work/Ebenezer Related/QuestionGen/'

# API 키 로드 및 환경변수 설정
load_api_keys(path + 'api_key.txt')

# print(os.environ['OPENAI_API_KEY'][:30])

"""올림포스 기본1
unit 8-15

->

시험지 지문 변형
2026-1A


감정변화
어휘/어법
빈칸추론
순서
요약
밑줄 번역

8 x 4 x 6

#Schema
"""

# ---------------------------------------
# Model
# ---------------------------------------

llm = ChatOpenAI(
    model="gpt-4.1-mini",
    temperature=0.3,
)

structured_llm = llm.with_structured_output(GeneratedQuestion)

PipelineStatus = Literal[
    "pending",
    "input_error",
    "input_passed",
    "generated",
    "validation_error",
    "validation_passed",
]

class QuestionState(TypedDict):
    source_paragraph: str
    student_paragraph: str
    OriginalQuestionNumber: int
    QuestionTypeKey: str

    generated: Optional[GeneratedQuestion]

    status: PipelineStatus
    errors: List[str]

# ---------------------------------------
# Pydantic output schema
# ---------------------------------------

class GeneratedQuestion(BaseModel):
    OriginalQuestionNumber: int = Field(
        description="Original source question number"
    )

    QuestionType: str = Field(
        description="Korean display label for the generated question type"
    )

    student_paragraph: str = Field(
        description="""The paragraph shown to the student.
        For insertion/ordering questions, this should be modified."""
    )

    question_stem: str = Field(
        description="Actual question stem being presented to the student"
    )

    given_sentence: Optional[str] = Field(
        default=None,
        description="Given sentence for sentence insertion questions"
    )

    choices: Optional[List[str]] = Field(
        default=None,
        description="Multiple choice options, if any"
    )

    answer: str = Field(
        description="Correct answer"
    )

    explanation: Optional[str] = Field(
        default=None,
        description="Justification for the answer, written entirely in Korean"
    )

"""#Question Types"""

# ---------------------------------------
# Question type registry
# ---------------------------------------

@dataclass(frozen=True)
class QuestionTypeSpec:
    label_ko: str
    rules: str
    modifies_paragraph: bool
    choice_count: Optional[int]
    answer_format: str
    min_source_sentences: Optional[int] = None


QUESTION_TYPES: dict[str, QuestionTypeSpec] = {
    "sentence_insertion": QuestionTypeSpec(
        label_ko="문장 삽입",
        rules=QType_Insertion,
        modifies_paragraph=True,
        choice_count=5,
        answer_format="marker",
        min_source_sentences=5,
    ),
}

# ---------------------------------------
# Question type prompt rules
# ---------------------------------------

QType_Insertion = """
For QuestionType "문장 삽입":

Task:
- Create a Korean 내신/수능-style sentence insertion question.

Rules:
- Select ONE complete sentence from the source paragraph as the given_sentence.
- The given_sentence must be copied exactly from the source paragraph.
- The given_sentence must be a full sentence, not a phrase, clause, or fragment.
- Do not paraphrase, rewrite, shorten, or grammatically repair the given_sentence.

Paragraph modification rules:
- Remove only the given_sentence from the paragraph.
- After removing the given_sentence, every other sentence from the source paragraph must remain in student_paragraph.
- Do not omit, summarize, merge, split, reorder, or rewrite any remaining sentence.
- Every remaining source sentence must appear exactly once.
- The original order of all remaining sentences must be preserved.
- Do not add, delete, or change punctuation in the remaining sentences except for adding insertion markers.

Marker rules:
- Add exactly five insertion markers: ①, ②, ③, ④, ⑤.
- The five markers must all appear in student_paragraph.
- Insert markers only between complete sentences.
- Do not place a marker inside a sentence.
- If the paragraph has more than five possible insertion positions, choose exactly five marker positions, but still keep the full remaining paragraph.
- Do not delete sentences just to make the number of markers fit.

Output rules:
- Put the modified paragraph in student_paragraph.
- Put the removed sentence in given_sentence.
- question_stem must be exactly:
  "글의 흐름으로 보아, 주어진 문장이 들어가기에 가장 적절한 곳은?"
- choices must be exactly ["①", "②", "③", "④", "⑤"].
- answer must be one of "①", "②", "③", "④", "⑤".
- explanation must be written entirely in Korean.
"""

"""# Nodes"""

# ---------------------------------------
# Eligibility node
# ---------------------------------------
def split_sentences(text: str) -> list[str]:
    text = text.strip()

    if not text:
        return []

    sentences = re.split(r"(?<=[.!?])\s+", text)

    return [
        sentence.strip()
        for sentence in sentences
        if sentence.strip()
    ]

def check_eligibility(state: QuestionState):
    type_spec = QUESTION_TYPES[state["QuestionTypeKey"]]

    source_sentences = split_sentences(state["source_paragraph"])
    sentence_count = len(source_sentences)

    if type_spec.min_source_sentences is not None:
        if sentence_count < type_spec.min_source_sentences:
            return {
                "status": "input_error",
                "errors": [
                    f"{type_spec.label_ko} 유형은 최소 "
                    f"{type_spec.min_source_sentences}개의 문장이 필요하지만, "
                    f"현재 지문은 {sentence_count}개 문장으로 분석되었습니다."
                ],
            }

    return {
        "status": "input_passed",
        "errors": [],
    }

def route_after_eligibility(state: QuestionState):
    if state["status"] == "input_passed":
        return "generate_question"

    return END

# ---------------------------------------
# Generation node
# ---------------------------------------

def generate_question(state: QuestionState):
    type_spec = QUESTION_TYPES[state["QuestionTypeKey"]]

    prompt = f"""
You are an English exam question generator.

Create ONE question based on the paragraph.

Return the result using the required structured format.

General rules:
- Do not invent information outside the source paragraph.
- Do not silently repair, rewrite, or improve the source paragraph.
- The final student-facing question stem must be written in Korean.
- The explanation must be written entirely in Korean.
- The output field QuestionType must be exactly:
  "{type_spec.label_ko}"

Question type-specific rules:
{type_spec.rules}

OriginalQuestionNumber:
{state["OriginalQuestionNumber"]}

QuestionTypeKey:
{state["QuestionTypeKey"]}

QuestionType:
{type_spec.label_ko}

Source paragraph:
{state["source_paragraph"]}

Current student-facing paragraph:
{state["student_paragraph"]}
"""

    result = structured_llm.invoke(prompt)

    return {
        "student_paragraph": result.student_paragraph,
        "generated": result,
        "status": "generated",
        "errors": [],
    }

# ---------------------------------------
# Validation node
# ---------------------------------------

def normalize_text(text: str) -> str:
    return " ".join(text.split())


def validate_generated_question(state: QuestionState):
    generated = state["generated"]

    if generated is None:
        return {
            "status": "validation_error",
            "errors": ["No generated question returned."],
        }

    errors = []

    type_spec = QUESTION_TYPES[state["QuestionTypeKey"]]

    source_sentences = split_sentences(state["source_paragraph"])
    student_text = normalize_text(generated.student_paragraph)

    if generated.QuestionType != type_spec.label_ko:
        errors.append(
            f"QuestionType should be '{type_spec.label_ko}', but got '{generated.QuestionType}'."
        )

    if state["QuestionTypeKey"] == "sentence_insertion":
        if not generated.given_sentence:
            errors.append("given_sentence is missing.")

        else:
            given = normalize_text(generated.given_sentence)
            normalized_source = normalize_text(state["source_paragraph"])

            if given not in normalized_source:
                errors.append("given_sentence does not appear exactly in source_paragraph.")

            if given in student_text:
                errors.append("given_sentence still appears in student_paragraph.")

            for sentence in source_sentences:
                normalized_sentence = normalize_text(sentence)

                if normalized_sentence == given:
                    continue

                if normalized_sentence not in student_text:
                    errors.append(
                        f"Missing source sentence from student_paragraph: {normalized_sentence}"
                    )

            for marker in ["①", "②", "③", "④", "⑤"]:
                count = generated.student_paragraph.count(marker)
                if count != 1:
                    errors.append(
                        f"Marker {marker} appears {count} times, expected exactly once."
                    )

            if generated.choices != ["①", "②", "③", "④", "⑤"]:
                errors.append("choices must be exactly ['①', '②', '③', '④', '⑤'].")

            if generated.answer not in ["①", "②", "③", "④", "⑤"]:
                errors.append("answer must be one of ①, ②, ③, ④, ⑤.")

    if errors:
        return {
            "status": "validation_error",
            "errors": errors,
        }

    return {
        "status": "validation_passed",
        "errors": [],
    }

# ---------------------------------------
# 7. Build graph
# ---------------------------------------

builder = StateGraph(QuestionState)

builder.add_node("check_eligibility", check_eligibility)
builder.add_node("generate_question", generate_question)
builder.add_node("validate_generated_question", validate_generated_question)

builder.add_edge(START, "check_eligibility")

builder.add_conditional_edges(
    "check_eligibility",
    route_after_eligibility,
    {
        "generate_question": "generate_question",
        END: END,
    },
)

builder.add_edge("generate_question", "validate_generated_question")
builder.add_edge("validate_generated_question", END)

graph = builder.compile()

"""#Interface"""

# ---------------------------------------
# Manual input
# ---------------------------------------

paragraph = """
Many people excuse perfectionism at work by claiming it is professionalism. Differentiating between the two is useful. Managing perfectionism does not mean dropping critical standards. It becomes a problem when your personal expectations become unmanageable, self-imposed demands that create more pressure than is needed. It is not permission for work sloppiness or low standards; rather it means spending less time on tasks that do not need the level of input you are providing. What are the acceptable standards of professionalism in your work and how do these compare with your own? With the busyness of workplaces these days, trying to achieve a benchmark of 110% perfect on everything can be a recipe for burnout. If you are a manager expecting this of others, you may be setting yourself up for failure.
"""

input_state = {
    "source_paragraph": paragraph,
    "student_paragraph": paragraph,
    "OriginalQuestionNumber": 1,
    "QuestionTypeKey": "sentence_insertion",
    "generated": None,
    "status": "pending",
    "errors": [],
}

# ---------------------------------------
# 9. Run graph
# ---------------------------------------

final_state = graph.invoke(input_state)

if final_state["status"] == "input_error":
    print("입력 오류:")
    for error in final_state["errors"]:
        print("-", error)

elif final_state["status"] == "validation_error":
    print("생성 결과 검증 실패:")
    for error in final_state["errors"]:
        print("-", error)

    if final_state["generated"]:
        print("\n생성된 원본 출력:")
        print(json.dumps(final_state["generated"].model_dump(), ensure_ascii=False, indent=2))

elif final_state["status"] == "validation_passed":
    generated = final_state["generated"]
    print(json.dumps(generated.model_dump(), ensure_ascii=False, indent=2))

else:
    print("Unexpected status:", final_state["status"])

